Update PR title once done with the command-issued version update (#131 redo)
conda-forge/webservices-dispatch-action pull request #132
Opened 2024-09-27 17:34 UTC by jaimergp

- Supersedes https://github.com/conda-forge/webservices-dispatch-action/pull/131
- Closes #130

2024-09-27 17:44 UTC, beckermr commented on webservices_dispatch_action/__main__.py
> +                    pr_num,
```suggestion
                    str(pr_num),
```

2024-09-27 17:53 UTC, beckermr commented
See the error on the version update job

```
2024-09-27 17:52:43,428 ERROR    webservices_dispatch_action.version_updater || error while trying to get PR title for conda-forge/cf-autotick-bot-test-package-feedstock#483
Traceback (most recent call last):
  File "/home/runner/work/_actions/conda-forge/webservices-dispatch-action/version-update-pr-title/webservices_dispatch_action/version_updater.py", line 129, in update_pr_title
    gh = github.Github(os.environ["GH_TOKEN"])
                       ~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'GH_TOKEN'
```

https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/actions/runs/11075355037/job/30776117735

This will go away once we remove the subprocess call.

2024-09-27 17:58 UTC, beckermr commented
Also yay for our previous attempt at isolation working for the case we designed it for!

2024-09-27 18:04 UTC, jaimergp commented
Hm, any reason we haven't set `concurrency.cancel-in-progress: true` in the GHA workflows??

2024-09-27 18:06 UTC, beckermr commented
If we cancel in progress jobs, we can leave the repos that we are testing with in an intermediate state. The tests might be robust enough to turn this off now, but I am not 100% sure.

2024-09-27 18:07 UTC, beckermr requested changes
Let's clean out the old entrypoint and main function as well.

2024-09-27 18:16 UTC, beckermr commented on webservices_dispatch_action/__main__.py
> +                    feedstock_dir, repo_name, input_version=input_version
The first argument needs to be the git_repo object, not an str.

2024-09-27 18:16 UTC, beckermr commented on webservices_dispatch_action/__main__.py
> +                    feedstock_dir, repo_name, input_version=input_version
```suggestion
                    git_repo, repo_name, input_version=input_version
```

2024-09-27 18:39 UTC, jaimergp commented
Looks like that worked, but I don't think we are testing the PR title change code paths because of this line:

https://github.com/conda-forge/webservices-dispatch-action/blob/a97415031972fa549fc0535163cd989f42a63291/webservices_dispatch_action/version_updater.py#L144

Any ideas? Or shall we debug that live?

2024-09-27 18:56 UTC, beckermr commented
We should be testing the title change in the tests. So I think we should change the pr title before we do the workflow dispatch, let the version update code change the title, test that the new title is correct, and then put back the original title.

2024-09-27 22:59 UTC, beckermr requested changes

2024-09-27 22:59 UTC, beckermr commented on webservices_dispatch_action/version_updater.py
> +        with sensitive_env():
You need to use the functions in the api utils to get the right token.

2024-09-27 23:00 UTC, beckermr commented on webservices_dispatch_action/version_updater.py
> +        with sensitive_env():
See this file: https://github.com/conda-forge/webservices-dispatch-action/blob/main/webservices_dispatch_action/api_sessions.py

2024-09-27 23:07 UTC, beckermr commented on webservices_dispatch_action/version_updater.py
> +        with sensitive_env():
This is still not right. The code uses a different token depending on which one is set. You should use the get actor token function and then feed that to function to make the api.

2024-09-27 23:08 UTC, beckermr commented on webservices_dispatch_action/version_updater.py
> +        with sensitive_env():
Never mind. This looks good!

2024-09-27 23:14 UTC, beckermr approved these changes

2024-09-27 23:16 UTC, jaimergp commented
Looks like it works now! 

<img width="978" alt="image" src="https://github.com/user-attachments/assets/227df34c-78a3-4b57-9b43-f53add47505e">

Thank you for all the guidance! <3

2024-09-27 23:34 UTC, beckermr commented
Thank you for the PR!

2024-09-28 00:14 UTC, merged

2024-09-28 00:32 UTC, jakirkham commented
Thanks Jaime and Matt! 🙏

This is a great idea 😄

Am wondering if it would also make sense to open PRs as drafts. The we could convert them to ready for review once all changes are pushed

2024-09-28 00:43 UTC, beckermr commented
We'll need changes in the webservices repo to but yes we can do that.